### ISSUE TITLE
fatal: repository 'https://github.com/0xe2-0x9a-0x9b/Go-SDL/' not found

### ISSUE THREAD

**Issue by captainju** [nsf/gotris#4]
Happend on "go get github.com/nsf/gotris"

**Comment by nsf** [comment]
Yes, the atom guy wiped his account from github, what can we do about it. :) I'll take a look if there is a similar SDL repo somewhere, if you want it now, submit a pull request.

**Comment by captainju** [comment]
Arf :'(
Don't you have a copy of it's repo that you can upload here as a fork ?

**Comment by nsf** [comment]
Sadly, no, I don't have a copy.
